[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonshadow',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'pallets/migrations',
    'bin/utils/moonkey'
]
exclude = [
    'bin/utils/moonkey'
]

[profile.release]
panic = 'unwind'
