[package]
name = "moonbeam-rpc-txpool"
version = '0.1.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
jsonrpc-core = "15.0.0"
ethereum-types = "0.9.0"
moonbeam-rpc-core-txpool = { path = "../../rpc-core/txpool" }
