name: Build

# Only executes when the checks are passing
on:
  workflow_run:
    workflows: ["Check Formatting"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      RUSTC: ${{ steps.get-rust-versions.outputs.rustc }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            node/standalone/target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          # Toolchain is autodetected from `rust-toolchain` file
          # https://github.com/actions-rs/toolchain#the-toolchain-file
          #toolchain: ${{ env.WASM_BUILD_TOOLCHAIN }}
          default: true
      - id: get-rust-versions
        run: |
          echo "::set-output name=rustc::$(rustc --version)"
      - name: Build Parachain Node
        run: cargo build --release --verbose --all
      - name: Build Standalone Node
        run: |
          cd node/standalone
          cargo build --release --verbose --all
      - name: Run tests
        run: cargo test --release --verbose --all
      - name: Typescript tests (against standalone node)
        run: |
          cd tests
          npm install
          BINARY_PATH='../node/standalone/target/release/moonbase-standalone' npm run test;
      - name: Save parachain binary
        run: |
          mkdir -p build/alphanet
          mkdir -p build/standalone
          cp target/release/moonbase-alphanet build/alphanet/moonbase-alphanet;
          cp node/standalone/target/release/moonbase-standalone build/standalone/moonbase-standalone;
      - name: Upload moonbase-alphanet node
        uses: actions/upload-artifact@v2
        with:
          name: moonbase-alphanet
          path: build/alphanet
      - name: Upload moonbase-standalone node
        uses: actions/upload-artifact@v2
        with:
          name: moonbase-standalone
          path: build/standalone
