name: Check Cargo

# Only executes once the Build workflow is done
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  check-cargo-toml:
    runs-on: ubuntu-latest
    steps:
      # We determine whether there are unmodified Cargo.lock files by:
      # 1. Asking git for a list of all modified files
      # 2. Using grep to reduce the list to only Cargo.lock files
      # 3. Counting the number of lines of output
      - run: |
          FILECOUNT=$(git diff-index --name-only HEAD | grep Cargo.lock | wc -l)
          if [[ $FILECOUNT -eq 0 ]]; then
            echo "All lock files are valid"
          else
            echo "The following Cargo.lock files have uncommitted changes"
            git diff-index --name-only HEAD | grep Cargo.lock
            false
          fi
