name: Release

# Using a single file workflow is the preferred solution for our CI over workflow_runs.
# 1. It generates only 1 action item in the list making it more readable
# 2. It includes the PR/Commit text in the action item
# 3. Artifacts are not available between workflows.

# This is only allowing pushes on the moonbeam repo for pull requests.
####### DO NOT CHANGE THIS !! #######
on: ["push"]

jobs:
  ####### Check files and formatting #######

  check-yarn:
    runs-on: ubuntu-latest
    steps:
      - name: check yarn
        run: |
          yarn --version
