name: Craft Release

# This workflow produces what is needed for a release.
# [Cond] Only executes once the Build workflow is done, only for master branch.
# [Cond] Only executes the jobs for a new vX.X.X tag.
on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed

jobs:
  publish-draft-release:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && startsWith(github.ref, 'refs/tags/v')
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: moonbeam
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Generate release text
        env:
          RUSTC: ${{ needs.build.outputs.rustc }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install changelogerator git toml
          ruby $GITHUB_WORKSPACE/moonbeam/scripts/github/generate_release_text.rb | tee release_text.md
      - name: Create draft release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Moonbase Alphanet ${{ github.ref }}
          body_path: ./release_text.md
          draft: true

  publish-runtimes:
    runs-on: ubuntu-latest
    needs: ["publish-draft-release"]
    if: github.event.action == 'labeled' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        runtime: ["moonbase-alphanet"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: moonbase-alphanet
          path: build/alphanet
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Get runtime version
        id: get-runtime-ver
        run: |
          runtime_ver="$(ruby -e 'require "./scripts/github/lib.rb"; puts get_runtime("${{ matrix.runtime }}")')"
          echo "::set-output name=runtime_ver::$runtime_ver"
      - name: Upload ${{ matrix.runtime }} wasm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: build/alphanet/${{ matrix.runtime }}-runtime.wasm
          asset_name: ${{ matrix.runtime }}-runtime-v${{ steps.get-runtime-ver.outputs.runtime_ver }}.wasm
          asset_content_type: application/wasm
      - name: Upload ${{ matrix.runtime }} node
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: build/alphanet/${{ matrix.runtime }}
          asset_name: ${{ matrix.runtime }}
          asset_content_type: application/octet-stream
      - name: Upload ${{ matrix.runtime }} specs plain
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: build/alphanet/${{ matrix.runtime }}-specs-plain.json
          asset_name: ${{ matrix.runtime }}-specs-plain.json
          asset_content_type: application/json
      - name: Upload ${{ matrix.runtime }} specs raw
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: build/alphanet/${{ matrix.runtime }}-specs-raw.json
          asset_name: ${{ matrix.runtime }}-specs-raw.json
          asset_content_type: application/json
      - name: Upload ${{ matrix.runtime }} genesis
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: build/alphanet/${{ matrix.runtime }}-genesis.txt
          asset_name: ${{ matrix.runtime }}-genesis.txt
          asset_content_type: text/plain
